App/urls.py
from django.conf.urls import url

from App import views

urlpatterns =[
    url(r'^index/',views.index,name='index'),
    url(r'^uploade/',views.uolade,name='uploade'),
    url(r'^userregister/',views.user_register,name='userregister'),
    url(r'^usercenter/',views.user_center,name='user_center')
]

djangoMTV/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'app/',include('App.urls',namespace='lele')),

]

App/models.py
from django.db import models

# Create your models here.

class UserModel(models.Model):
    u_name = models.CharField(max_length=16)
    u_password = models.CharField(max_length=128)

    u_icon = models.ImageField(upload_to='icons')

App/views.py
import hashlib
import os
import uuid


from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from App.models import UserModel
from djangoMTV import settings


def index(request):
    return HttpResponse('index')


def uolade(request):
    if request.method == 'GET':
        return render(request, 'uoloade.html')
    elif request.method == 'POST':
        icon = request.FILES.get('icon')
        save_file_path = os.path.join(settings.BASE_DIR, 'static/uploade/' + str(uuid.uuid4()) + str(icon))

        with open(save_file_path, 'wb') as save_file:
            for part in icon.chunks():
                save_file.write(part)
                save_file.flush()
        return HttpResponse('上传成功')


def user_register(request):
    if request.method == 'GET':
        return render(request, 'user_register.html')
    elif request.method == 'POST':
        icon = request.FILES.get('icon')

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = UserModel()
        user.u_name = username
        password = genart_password(password)
        user.u_password = password
        user.u_icon = icon

        user.save()
        response = HttpResponse('注册成功')

        response.set_cookie('username', username)

        return response


def user_center(request):
    username = request.COOKIES.get("username")

    if not username:
        return render(request, 'user_center.html', context={"is_login": False})

    user = UserModel.objects.get(u_name=username)

    data = {
        "is_login": True,
        "username": user.u_name,
        "icon": "/static/uploade/" + user.u_icon.url
    }

    return render(request, 'user_center.html', context=data)

def genart_password(password):
    sha512 = hashlib.sha512()
    sha512.update(password.encode('utf8'))
    return sha512.hexdigest()

templates/uoloade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文件上传</title>
</head>
<body>
<form action="{% url 'lele:uploade' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <span>用户名:</span><input type="text" name="username" placeholder="请输入用户名">
    <br>
    <span>头像</span><input type="file" name="icon">
    <br>
    <input type="submit">

</form>
</body>
</html>

templates/user_center.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户信息</title>
</head>
<body>
{% if is_login %}
    <h2>欢迎回来:{{ username }}</h2>
    <img src="{{ icon }}" alt="头像">
    {% else %}
    <h2>游客你好</h2>
{% endif %}


</body>
</html>

templates/user_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
</head>
<body>
<form action="{% url 'lele:userregister' %}" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    <span>用户名:</span><input type="text" name="username" placeholder="请输入用户名">
    <br>
    <span>密码:</span><input type="text" name="password" placeholder="请输入密码">
    <br>
    <span>头像</span><input type="file" name="icon">
    <br>
    <input type="submit">
</form>
</body>
</html>